name: Publish Package to npmjs
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  get-pnpm-version:
    runs-on: ubuntu-latest
    outputs:
      pnpm-version: ${{ steps.get-version.outputs.pnpm-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract pnpm version
        id: get-version
        run: echo "pnpm-version=$(jq -r '.packageManager' package.json | sed 's/pnpm@//')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: get-pnpm-version
    strategy:
      matrix:
        node-version: [20]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ needs.get-pnpm-version.outputs.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run build
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: pnpm -r publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
